### ISSUE TITLE
_combine_old -> _combine in weighting.py

### ISSUE THREAD

**Issue by lucaskolstad** [lucaskolstad/rBCM#3]
The `_combine_old` function implements EQ. 21 and EQ. 22 in [the paper](https://arxiv.org/pdf/1502.02843.pdf). This was implemented simply to ease correctness verification, but has significant performance issues that negate much of the rBCM's performance benefits to begin with. It's replacement `_combine` leverages `np.einsum` from the `numpy` package to boost the performance, but verification that it matches the old one is needed.

It's probably wise to not assume `_combine_old` is perfectly correct either, it should have some testing as well.

**Comment by joshring** [comment]
Have you tried the trivial solution:
numba 
http://numba.pydata.org/

**Comment by lucaskolstad** [comment]
No I haven't used Numba before unfortunately, but I've read some on it and I'm completely open to that option as this issue really just needs anything that can speed up the triple nested for loops.

**Comment by joshring** [comment]
It is the perfect solution to nested for loops and heavy numpy code, it falls over on function calls to non numpy code however, and falls back to "nopython" mode, which equates to "no performance benefit" mode so be careful to use it like:

`@numba.njit`
`def function( args1, args2 ):`
...


see: http://numba.pydata.org/numba-doc/0.33.0/user/jit.html#nopython

**Comment by lucaskolstad** [comment]
Ya that seems a much smarter solution to me than fighting with the `np.einsum` approach. I'll see how it goes once I can sit down and focus on it for more time. I would also accept a PR on this or any other cleanup/improvements/redesign because it's all pretty rough. Thanks for the tip on avoiding the fallback as well.

**Comment by joshring** [comment]
I can only see a trivial amount of time spent in this function, compared to the standard deviation calculation. (<1s vs 50s)

I tried the numba approach also and gained very little. I think we can close this issue and keep the old `_combine_old` approach for now.

**Comment by lucaskolstad** [comment]
Ok perfect thanks for investigating this! I'll make that change to keep the old combine only and close this once I do.
