### ISSUE TITLE
Locality = true causing issues

### ISSUE THREAD

**Issue by joshring** [lucaskolstad/rBCM#6]
With locality = False
![locality_false](https://user-images.githubusercontent.com/3970616/27006786-a61ae5a6-4e35-11e7-83ea-242fbd022d22.png)

Compared to with locality = True
![locality_true](https://user-images.githubusercontent.com/3970616/27006779-4d5416fe-4e35-11e7-9999-092ba59cfc71.png)

**Comment by joshring** [comment]
Suggested fix:
Change the default kernel with locality=True to `Matern(length_scale=1.0, nu=3/2)`.
It helps the solution cope with discontinuities at the edge of the clusters.

It is not perfect and I think there's still work to do here, but it makes it a better starting default at least.

With `Matern(length_scale=1.0, nu=3/2)`:
![matern_3_2 copes better for local_true](https://user-images.githubusercontent.com/3970616/27014833-8fe250b2-4ef8-11e7-99ff-f0f1429c2a10.png)


Looking at the log(absolute_error) is informative also, the model edges are clearly visible.
![matern_3_2 copes better for local_true_log_abs_error](https://user-images.githubusercontent.com/3970616/27014849-e0cf31e8-4ef8-11e7-90b1-4808db881f7c.png)

**Comment by lucaskolstad** [comment]
I'm in favor of this. I think you could assign `self.kernel = Matern(length_scale=1.0, nu=3/2)` directly after [this line](https://github.com/lucaskolstad/rBCM/blob/master/rBCM/rbcm.py#L104) in the current code to do that. In case you didn't see it, I just pushed a new commit that refactored some code! But no changes to the actual logic or defaults was made, it was just reorganized to separate things out.

**Comment by joshring** [comment]
Ah I think our commit and message"crossed in the post", I thought it made sense to put it in the init function, but it's probably style change really.

**Comment by lucaskolstad** [comment]
Resolved in PR 04a22e7. I'm fine with it being in the init where you had it in your commit.
